In [3]:
import numpy as np

In [4]:
names = np.array([
    'Ali', 'Sara', 'John', 'Aisha',"David",
    "Fatima","Rahul","Zoya","Kiran","Ahmed"
])

department = np.array([
    'IT', 'HR', 'IT', 'Finance', 'Marketing',"HR","IT","Finance","Marketing","IT"
])

salary = np.array([
    55000,45000,75000,82000,50000,48000,39000,91000,52000,88000
])

experience = np.array([
    2,1,5,7,3,2,1,8,4,6
])

rating = np.array([
    4,2,5,5,4,4,2,5,3,5
])


Total Names

In [5]:
print(len(names))

10


Average Salary

In [6]:
avg_salary = np.mean(salary)
print(avg_salary)

62500.0


Highest Salarym

In [7]:
highest_salary = np.argmax(salary)
print(names[highest_salary])
print(salary[highest_salary])


Zoya
91000


Lowest Salarym

In [8]:
lowest_salary = np.argmin(salary)
print(names[lowest_salary])
print(salary[lowest_salary])


Rahul
39000


IT Employee

In [9]:
it_emp = department == 'IT'
it_avg_salary = np.mean(salary[it_emp])
print(it_avg_salary)

64250.0


HR Employee

In [10]:
hr_emp = department == 'HR'
print(names[hr_emp])

['Sara' 'Fatima']


Employee with more than five years of Experience

In [11]:
senior_emp = experience > 5
print(names[senior_emp])
print(experience[senior_emp])


['Aisha' 'Zoya' 'Ahmed']
[7 8 6]


Average Salary of Experienced Employees


In [12]:
experience_avg_salary = np.mean(experience[senior_emp])
print(experience_avg_salary)

7.0


Bonus Calculation

Company gives:

20% bonus if rating = 5
10% bonus otherwise

In [13]:
bonus = np.where(rating == 5, salary * 0.20, salary * 0.10 )
print(bonus)

[ 5500.  4500. 15000. 16400.  5000.  4800.  3900. 18200.  5200. 17600.]


Final Salary After Bonus

In [14]:
final_salary = salary + bonus
print(final_salary)

[ 60500.  49500.  90000.  98400.  55000.  52800.  42900. 109200.  57200.
 105600.]


Promotion Eligibility

In [15]:
promotion = (experience>=5) & (rating>=4)
print(names[promotion])

['John' 'Aisha' 'Zoya' 'Ahmed']


Sort Employees by Salary Descending

In [16]:
sorted_index = np.argsort(salary)[::-1]
print(names[sorted_index])


['Zoya' 'Ahmed' 'Aisha' 'John' 'Ali' 'Kiran' 'David' 'Fatima' 'Sara'
 'Rahul']


Top 3 Highest Paid Employees

In [17]:
print(names[sorted_index][:3])

['Zoya' 'Ahmed' 'Aisha']


Employees Earning More Than Average

In [18]:
avg_earning = np.mean(salary)
highest_paid = salary > avg_earning
print(names[highest_paid])

['John' 'Aisha' 'Zoya' 'Ahmed']


 Add New Employee

In [19]:
names = np.append(names, 'hafeez')

department = np.append(department, 'IT')

salary = np.append(salary, 65000)

experience = np.append(experience, 3)

rating = np.append(rating, 4)

In [20]:
bonus = np.where(experience > 5, 5000, 2000)
final_salary = salary+bonus

Remove Low Performers

In [21]:

# good_emp = rating>=3
#
# names = names[good_emp]
# salary = salary[good_emp]
# department = department[good_emp]
# experience = experience[good_emp]
# rating = rating[good_emp]
# final_salary = final_salary[good_emp]
# # print(len(names))
# # print(len(salary))
# # print(len(department))
# # print(len(experience))
# # print(len(rating))

good_emp = rating >= 3

names = names[good_emp]
department = department[good_emp]
salary = salary[good_emp]
experience = experience[good_emp]
rating = rating[good_emp]
final_salary = final_salary[good_emp]

Save Report to CSV

In [22]:
report = np.column_stack((
    names,
    department,
    salary,
    experience,
    rating,
    final_salary
))

np.savetxt(
    "employee_report.csv",
    report,
    delimiter=',',
    fmt='%s',
    header='Names, Department, Salary, Experience, Rating, Final Salary',
    comments=''
)

print('Report Saved')

Report Saved


Finance Department Average Salary

In [25]:
Finance_department = department == 'Finance'
Finance_avg = np.mean(salary[Finance_department])
print(Finance_avg)

86500.0


In [26]:
top_rating = rating == 5
print(names[top_rating])

['John' 'Aisha' 'Zoya' 'Ahmed']


In [27]:
salary_below_50 = salary <50000
print(names[salary_below_50])

['Fatima']


In [35]:
emp_exp = np.argsort(experience)[::-1]
most_exp_emp = names[emp_exp][0]
print(most_exp_emp)

['Zoya' 'Aisha' 'Ahmed' 'John' 'Kiran' 'hafeez' 'David' 'Fatima' 'Ali']
[8 7 6 5 4 3 3 2 2]
Zoya


Salary Greater than 50000 10% Tax

In [36]:
tax = np.where(salary>50000, salary*0.10, salary*0.05)
print('Tax Deduction:',tax)

Tax Deduction: [5500. 7500. 8200. 2500. 2400. 9100. 5200. 8800. 6500.]


Yearly Salary

In [37]:
yearly_salary = salary*12
print('Yearly salary:',yearly_salary)

Yearly salary: [ 660000  900000  984000  600000  576000 1092000  624000 1056000  780000]


Create Employee Grades

In [38]:
grades = np.where(
    rating == 5, 'A',
    np.where(
        rating == 4, 'B',
        np.where(
            rating == 3, 'C','D'
        )
    )
)
print('Employee Grades:',grades)

Employee Grades: ['B' 'A' 'A' 'B' 'B' 'A' 'C' 'A' 'B']


Find Department with highest average salary

In [46]:
it_dept_avg =np.mean( salary[department == 'IT'])
hr_dept_avg =np.mean( salary[department == 'HR'])
finance_dept_avg =np.mean( salary[department == 'Finance'])
marketing_dept_avg =np.mean(salary[department == 'Marketing'])

print(it_dept_avg)
print(hr_dept_avg)
print(finance_dept_avg)
print(marketing_dept_avg)

avg_list = np.array([
    it_dept_avg,
    hr_dept_avg,
    finance_dept_avg,
    marketing_dept_avg
])
dept_names = np.array(['IT', 'HR', 'Finance', 'Marketing'])


dept_highest_avg = dept_names[np.argmax(avg_list)]
print('Department with Highest Average is :', dept_highest_avg)

70750.0
48000.0
86500.0
51000.0
Department with Highest Average is : Finance
